spring:
  application:
    name: "service1"

  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: kotlinspring
  jackson:
    default-property-inclusion: non_null

  cloud:
    config:
      uri: http://localhost:8888


eureka:
  client:
    healthcheck:
      enabled: true

server:
  port: 0